[folders]
paths = d:\wrk\zig\zig-gtlogj
timestamp = @timestamp
level = level
message = message
output = [{level}] {timestamp}: {message}

[profile.timed]
output = {timestamp:datetime} [{level}]: {message}

[profile.custom]
output = {timestamp} |{custom_field}|{missing_field}|: {message}
