[folders]
; path is ommited for this test config so it is easier to use to try examples from readme
; paths = /path/to/logs
timestamp = @timestamp
level = level
message = message
output = [{level}] {timestamp}: {message}

[profile.timed]
output = {timestamp:datetime} [{level}]: {message}

[profile.custom]
output = {timestamp} |{custom_field}|{missing_field}|: {message}

